### ISSUE TITLE
Automatically wait after hitting FloodWait Error instead of quitting

### ISSUE THREAD

**Issue by tissole** [aahnik/telegram-chat-forward#9]
I want to clone some big Telegram channels. Your program works pretty well on small ones, but on very big channels with many posts, it takes very long, weeks long. It happens because the program stops after copying some posts. And I have to start it manually.

Obviously, I can't stand all day in front of the computer to do that. So I can only copy limited posts daily. Can you modify the program to start automatically after it waits? That will save a lot of time.

Another useful feature will be to deploy on Heroku because even if the program is able to run automatically on PC it still takes days of running continuously to clone very big channels. The electricity bill goes up quickly :(

**Comment by aahnik** [comment]
Your feature requests are very much valid. And I also thought about them earlier. Will add them soon.

**Comment by aahnik** [comment]
How to run in Heroku ? [Read this](https://github.com/aahnik/telegram-chat-forward/discussions/10)

The program will no more quit after hitting FloodWaitError. It will wait for the required no. of seconds. Please test it.
